stages:
  load_data:
    cmd: python src/data/load_data.py
    deps:
      - src/data/load_data.py
      - data/raw/big_student_clear_third_version.csv
    outs:
      - data/processed/cleaned_data.csv

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/processed/cleaned_data.csv
    outs:
      - data/processed/features.csv

  train_model:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed/features.csv
    outs:
      - models/lgb_model.txt